/*!
******************************************************************************
@file   : cr_perip_reg_defs.h

@brief  Saturn Top Level register defintions

@Author <Autogenerated>

		<b>Copyright 2010 by Imagination Technologies Limited.</b>\n
         All rights reserved.  No part of this software, either
         material or conceptual may be copied or distributed,
         transmitted, transcribed, stored in a retrieval system
         or translated into any human or computer language in any
         form by any means, electronic, mechanical, manual or
         other-wise, or disclosed to the third parties without the
         express written permission of Imagination Technologies
         Limited, Home Park Estate, Kings Langley, Hertfordshire,
         WD4 8LZ, U.K.

******************************************************************************/

#ifndef __CR_PERIP_REG_DEFS_H__
#define __CR_PERIP_REG_DEFS_H__

/* This line just means we can write C here and C++ elsewhere when it
** picks up the header file will know that all these functions are
** mangled up C wise instead of C++ wise.  See also the } way below.
*/
#ifdef __cplusplus
extern "C" {
#endif


/* Hardware register definitions */

/* -------------------- Register CR_PERIP_SRST -------------------- */

#define CR_PERIP_SRST_OFFSET                      (0x0000)

/* Field CR_PERIP_SCB0_SOFT_RESET */
#define CR_PERIP_SCB0_SOFT_RESET_OFFSET           CR_PERIP_SRST_OFFSET
#define CR_PERIP_SCB0_SOFT_RESET_SHIFT            (0)
#define CR_PERIP_SCB0_SOFT_RESET_MASK             (0x00000001)
#define CR_PERIP_SCB0_SOFT_RESET_FLAGS            (REG_VOL)
#define CR_PERIP_SCB0_SOFT_RESET_LENGTH           (1)

/* Field CR_PERIP_SCB1_SOFT_RESET */
#define CR_PERIP_SCB1_SOFT_RESET_OFFSET           CR_PERIP_SRST_OFFSET
#define CR_PERIP_SCB1_SOFT_RESET_SHIFT            (1)
#define CR_PERIP_SCB1_SOFT_RESET_MASK             (0x00000002)
#define CR_PERIP_SCB1_SOFT_RESET_FLAGS            (REG_VOL)
#define CR_PERIP_SCB1_SOFT_RESET_LENGTH           (1)

/* Field CR_PERIP_SCB2_SOFT_RESET */
#define CR_PERIP_SCB2_SOFT_RESET_OFFSET           CR_PERIP_SRST_OFFSET
#define CR_PERIP_SCB2_SOFT_RESET_SHIFT            (2)
#define CR_PERIP_SCB2_SOFT_RESET_MASK             (0x00000004)
#define CR_PERIP_SCB2_SOFT_RESET_FLAGS            (REG_VOL)
#define CR_PERIP_SCB2_SOFT_RESET_LENGTH           (1)

/* Field CR_PERIP_UART0_SOFT_RESET */
#define CR_PERIP_UART0_SOFT_RESET_OFFSET          CR_PERIP_SRST_OFFSET
#define CR_PERIP_UART0_SOFT_RESET_SHIFT           (4)
#define CR_PERIP_UART0_SOFT_RESET_MASK            (0x00000010)
#define CR_PERIP_UART0_SOFT_RESET_FLAGS           (REG_VOL)
#define CR_PERIP_UART0_SOFT_RESET_LENGTH          (1)

/* Field CR_PERIP_UART1_SOFT_RESET */
#define CR_PERIP_UART1_SOFT_RESET_OFFSET          CR_PERIP_SRST_OFFSET
#define CR_PERIP_UART1_SOFT_RESET_SHIFT           (5)
#define CR_PERIP_UART1_SOFT_RESET_MASK            (0x00000020)
#define CR_PERIP_UART1_SOFT_RESET_FLAGS           (REG_VOL)
#define CR_PERIP_UART1_SOFT_RESET_LENGTH          (1)

/* Field CR_PERIP_SPI_SOFT_RESET */
#define CR_PERIP_SPI_SOFT_RESET_OFFSET            CR_PERIP_SRST_OFFSET
#define CR_PERIP_SPI_SOFT_RESET_SHIFT             (6)
#define CR_PERIP_SPI_SOFT_RESET_MASK              (0x00000040)
#define CR_PERIP_SPI_SOFT_RESET_FLAGS             (REG_VOL)
#define CR_PERIP_SPI_SOFT_RESET_LENGTH            (1)

/* Field CR_PERIP_SPIM1_SOFT_RESET */
#define CR_PERIP_SPIM1_SOFT_RESET_OFFSET          CR_PERIP_SRST_OFFSET
#define CR_PERIP_SPIM1_SOFT_RESET_SHIFT           (8)
#define CR_PERIP_SPIM1_SOFT_RESET_MASK            (0x00000100)
#define CR_PERIP_SPIM1_SOFT_RESET_FLAGS           (REG_VOL)
#define CR_PERIP_SPIM1_SOFT_RESET_LENGTH          (1)

/* Field CR_PERIP_ETS_SOFT_RESET */
#define CR_PERIP_ETS_SOFT_RESET_OFFSET            CR_PERIP_SRST_OFFSET
#define CR_PERIP_ETS_SOFT_RESET_SHIFT             (9)
#define CR_PERIP_ETS_SOFT_RESET_MASK              (0x00000200)
#define CR_PERIP_ETS_SOFT_RESET_FLAGS             (REG_VOL)
#define CR_PERIP_ETS_SOFT_RESET_LENGTH            (1)

/* Field CR_PERIP_DMAC_SOFT_RESET */
#define CR_PERIP_DMAC_SOFT_RESET_OFFSET           CR_PERIP_SRST_OFFSET
#define CR_PERIP_DMAC_SOFT_RESET_SHIFT            (10)
#define CR_PERIP_DMAC_SOFT_RESET_MASK             (0x00000400)
#define CR_PERIP_DMAC_SOFT_RESET_FLAGS            (REG_VOL)
#define CR_PERIP_DMAC_SOFT_RESET_LENGTH           (1)

/* Field CR_PERIP_ARBITER_SOFT_RESET */
#define CR_PERIP_ARBITER_SOFT_RESET_OFFSET        CR_PERIP_SRST_OFFSET
#define CR_PERIP_ARBITER_SOFT_RESET_SHIFT         (11)
#define CR_PERIP_ARBITER_SOFT_RESET_MASK          (0x00000800)
#define CR_PERIP_ARBITER_SOFT_RESET_FLAGS         (REG_VOL)
#define CR_PERIP_ARBITER_SOFT_RESET_LENGTH        (1)

/* Field CR_PERIP_USB_SOFT_HRESET */
#define CR_PERIP_USB_SOFT_HRESET_OFFSET           CR_PERIP_SRST_OFFSET
#define CR_PERIP_USB_SOFT_HRESET_SHIFT            (15)
#define CR_PERIP_USB_SOFT_HRESET_MASK             (0x00008000)
#define CR_PERIP_USB_SOFT_HRESET_FLAGS            (REG_VOL)
#define CR_PERIP_USB_SOFT_HRESET_LENGTH           (1)

/* Field CR_PERIP_USB_SOFT_PRRESET */
#define CR_PERIP_USB_SOFT_PRRESET_OFFSET          CR_PERIP_SRST_OFFSET
#define CR_PERIP_USB_SOFT_PRRESET_SHIFT           (16)
#define CR_PERIP_USB_SOFT_PRRESET_MASK            (0x00010000)
#define CR_PERIP_USB_SOFT_PRRESET_FLAGS           (REG_VOL)
#define CR_PERIP_USB_SOFT_PRRESET_LENGTH          (1)

/* Field CR_PERIP_USB_PHY_PORTRESET */
#define CR_PERIP_USB_PHY_PORTRESET_OFFSET         CR_PERIP_SRST_OFFSET
#define CR_PERIP_USB_PHY_PORTRESET_SHIFT          (17)
#define CR_PERIP_USB_PHY_PORTRESET_MASK           (0x00020000)
#define CR_PERIP_USB_PHY_PORTRESET_FLAGS          (REG_VOL)
#define CR_PERIP_USB_PHY_PORTRESET_LENGTH         (1)

/* Field CR_PERIP_USB_PHY_PON_RESET */
#define CR_PERIP_USB_PHY_PON_RESET_OFFSET         CR_PERIP_SRST_OFFSET
#define CR_PERIP_USB_PHY_PON_RESET_SHIFT          (18)
#define CR_PERIP_USB_PHY_PON_RESET_MASK           (0x00040000)
#define CR_PERIP_USB_PHY_PON_RESET_FLAGS          (REG_VOL)
#define CR_PERIP_USB_PHY_PON_RESET_LENGTH         (1)

/* Field CR_PERIP_DISEQC0_SOFT_RESET */
#define CR_PERIP_DISEQC0_SOFT_RESET_OFFSET        CR_PERIP_SRST_OFFSET
#define CR_PERIP_DISEQC0_SOFT_RESET_SHIFT         (19)
#define CR_PERIP_DISEQC0_SOFT_RESET_MASK          (0x00080000)
#define CR_PERIP_DISEQC0_SOFT_RESET_FLAGS         (REG_VOL)
#define CR_PERIP_DISEQC0_SOFT_RESET_LENGTH        (1)

/* Field CR_PERIP_DISEQC1_SOFT_RESET */
#define CR_PERIP_DISEQC1_SOFT_RESET_OFFSET        CR_PERIP_SRST_OFFSET
#define CR_PERIP_DISEQC1_SOFT_RESET_SHIFT         (20)
#define CR_PERIP_DISEQC1_SOFT_RESET_MASK          (0x00100000)
#define CR_PERIP_DISEQC1_SOFT_RESET_FLAGS         (REG_VOL)
#define CR_PERIP_DISEQC1_SOFT_RESET_LENGTH        (1)

/* Complete Register Definition */
#define CR_PERIP_SRST_REG_OFFSET                  CR_PERIP_SRST_OFFSET
#define CR_PERIP_SRST_REG_SHIFT                   (0)
#define CR_PERIP_SRST_REG_MASK                    (0xFFFFFFFF)
#define CR_PERIP_SRST_REG_FLAGS                   (REG_VOL)
#define CR_PERIP_SRST_REG_LENGTH                  (32)


/* -------------------- Register CR_PERIP_RESET_CFG -------------------- */

#define CR_PERIP_RESET_CFG_OFFSET                 (0x0004)

/* Field CR_PERIP_RESET_CFG */
/*#define CR_PERIP_RESET_CFG_OFFSET               CR_PERIP_RESET_CFG_OFFSET*/
#define CR_PERIP_RESET_CFG_SHIFT                  (0)
#define CR_PERIP_RESET_CFG_MASK                   (0x001FFFFF)
#define CR_PERIP_RESET_CFG_FLAGS                  (REG_VOL)
#define CR_PERIP_RESET_CFG_LENGTH                 (21)

/* Field CR_SATURN_CORE_CFG */
#define CR_SATURN_CORE_CFG_OFFSET                 CR_PERIP_RESET_CFG_OFFSET
#define CR_SATURN_CORE_CFG_SHIFT                  (28)
#define CR_SATURN_CORE_CFG_MASK                   (0xF0000000)
#define CR_SATURN_CORE_CFG_FLAGS                  (REG_VOL)
#define CR_SATURN_CORE_CFG_LENGTH                 (4)

/* Complete Register Definition */
#define CR_PERIP_RESET_CFG_REG_OFFSET             CR_PERIP_RESET_CFG_OFFSET
#define CR_PERIP_RESET_CFG_REG_SHIFT              (0)
#define CR_PERIP_RESET_CFG_REG_MASK               (0xFFFFFFFF)
#define CR_PERIP_RESET_CFG_REG_FLAGS              (REG_VOL)
#define CR_PERIP_RESET_CFG_REG_LENGTH             (32)


/* -------------------- Register CR_PERIP_CLKEN -------------------- */

#define CR_PERIP_CLKEN_OFFSET                     (0x0010)

/* Field CR_PERIP_SCB0_SYS_CLK_EN */
#define CR_PERIP_SCB0_SYS_CLK_EN_OFFSET           CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_SCB0_SYS_CLK_EN_SHIFT            (0)
#define CR_PERIP_SCB0_SYS_CLK_EN_MASK             (0x00000001)
#define CR_PERIP_SCB0_SYS_CLK_EN_FLAGS            (REG_VOL)
#define CR_PERIP_SCB0_SYS_CLK_EN_LENGTH           (1)

/* Field CR_PERIP_SCB1_SYS_CLK_EN */
#define CR_PERIP_SCB1_SYS_CLK_EN_OFFSET           CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_SCB1_SYS_CLK_EN_SHIFT            (1)
#define CR_PERIP_SCB1_SYS_CLK_EN_MASK             (0x00000002)
#define CR_PERIP_SCB1_SYS_CLK_EN_FLAGS            (REG_VOL)
#define CR_PERIP_SCB1_SYS_CLK_EN_LENGTH           (1)

/* Field CR_PERIP_SCB2_SYS_CLK_EN */
#define CR_PERIP_SCB2_SYS_CLK_EN_OFFSET           CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_SCB2_SYS_CLK_EN_SHIFT            (2)
#define CR_PERIP_SCB2_SYS_CLK_EN_MASK             (0x00000004)
#define CR_PERIP_SCB2_SYS_CLK_EN_FLAGS            (REG_VOL)
#define CR_PERIP_SCB2_SYS_CLK_EN_LENGTH           (1)

/* Field CR_PERIP_UART0_SYS_CLK_EN */
#define CR_PERIP_UART0_SYS_CLK_EN_OFFSET          CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_UART0_SYS_CLK_EN_SHIFT           (3)
#define CR_PERIP_UART0_SYS_CLK_EN_MASK            (0x00000008)
#define CR_PERIP_UART0_SYS_CLK_EN_FLAGS           (REG_VOL)
#define CR_PERIP_UART0_SYS_CLK_EN_LENGTH          (1)

/* Field CR_PERIP_UART1_SYS_CLK_EN */
#define CR_PERIP_UART1_SYS_CLK_EN_OFFSET          CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_UART1_SYS_CLK_EN_SHIFT           (4)
#define CR_PERIP_UART1_SYS_CLK_EN_MASK            (0x00000010)
#define CR_PERIP_UART1_SYS_CLK_EN_FLAGS           (REG_VOL)
#define CR_PERIP_UART1_SYS_CLK_EN_LENGTH          (1)

/* Field CR_PERIP_SPIM_SYS_CLK_EN */
#define CR_PERIP_SPIM_SYS_CLK_EN_OFFSET           CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_SPIM_SYS_CLK_EN_SHIFT            (5)
#define CR_PERIP_SPIM_SYS_CLK_EN_MASK             (0x00000020)
#define CR_PERIP_SPIM_SYS_CLK_EN_FLAGS            (REG_VOL)
#define CR_PERIP_SPIM_SYS_CLK_EN_LENGTH           (1)

/* Field CR_PERIP_SPIS_SYS_CLK_EN */
#define CR_PERIP_SPIS_SYS_CLK_EN_OFFSET           CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_SPIS_SYS_CLK_EN_SHIFT            (6)
#define CR_PERIP_SPIS_SYS_CLK_EN_MASK             (0x00000040)
#define CR_PERIP_SPIS_SYS_CLK_EN_FLAGS            (REG_VOL)
#define CR_PERIP_SPIS_SYS_CLK_EN_LENGTH           (1)

/* Field CR_PERIP_SPIM1_SYS_CLK_EN */
#define CR_PERIP_SPIM1_SYS_CLK_EN_OFFSET          CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_SPIM1_SYS_CLK_EN_SHIFT           (7)
#define CR_PERIP_SPIM1_SYS_CLK_EN_MASK            (0x00000080)
#define CR_PERIP_SPIM1_SYS_CLK_EN_FLAGS           (REG_VOL)
#define CR_PERIP_SPIM1_SYS_CLK_EN_LENGTH          (1)

/* Field CR_PERIP_USB_SYS_CLK_EN */
#define CR_PERIP_USB_SYS_CLK_EN_OFFSET            CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_USB_SYS_CLK_EN_SHIFT             (8)
#define CR_PERIP_USB_SYS_CLK_EN_MASK              (0x00000100)
#define CR_PERIP_USB_SYS_CLK_EN_FLAGS             (REG_VOL)
#define CR_PERIP_USB_SYS_CLK_EN_LENGTH            (1)

/* Field CR_PERIP_DMAC_SYS_CLK_EN */
#define CR_PERIP_DMAC_SYS_CLK_EN_OFFSET           CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_DMAC_SYS_CLK_EN_SHIFT            (9)
#define CR_PERIP_DMAC_SYS_CLK_EN_MASK             (0x00000200)
#define CR_PERIP_DMAC_SYS_CLK_EN_FLAGS            (REG_VOL)
#define CR_PERIP_DMAC_SYS_CLK_EN_LENGTH           (1)

/* Field CR_PERIP_DISEQC0_SYS_CLK_EN */
#define CR_PERIP_DISEQC0_SYS_CLK_EN_OFFSET        CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_DISEQC0_SYS_CLK_EN_SHIFT         (10)
#define CR_PERIP_DISEQC0_SYS_CLK_EN_MASK          (0x00000400)
#define CR_PERIP_DISEQC0_SYS_CLK_EN_FLAGS         (REG_VOL)
#define CR_PERIP_DISEQC0_SYS_CLK_EN_LENGTH        (1)

/* Field CR_PERIP_DISEQC1_SYS_CLK_EN */
#define CR_PERIP_DISEQC1_SYS_CLK_EN_OFFSET        CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_DISEQC1_SYS_CLK_EN_SHIFT         (11)
#define CR_PERIP_DISEQC1_SYS_CLK_EN_MASK          (0x00000800)
#define CR_PERIP_DISEQC1_SYS_CLK_EN_FLAGS         (REG_VOL)
#define CR_PERIP_DISEQC1_SYS_CLK_EN_LENGTH        (1)

/* Complete Register Definition */
#define CR_PERIP_CLKEN_REG_OFFSET                 CR_PERIP_CLKEN_OFFSET
#define CR_PERIP_CLKEN_REG_SHIFT                  (0)
#define CR_PERIP_CLKEN_REG_MASK                   (0xFFFFFFFF)
#define CR_PERIP_CLKEN_REG_FLAGS                  (REG_VOL)
#define CR_PERIP_CLKEN_REG_LENGTH                 (32)


/* -------------------- Register CR_PERIP_CLKSTATUS -------------------- */

#define CR_PERIP_CLKSTATUS_OFFSET                 (0x0014)

/* Field CR_PERIP_SCB0_SYS_CLK_STATUS */
#define CR_PERIP_SCB0_SYS_CLK_STATUS_OFFSET       CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_SCB0_SYS_CLK_STATUS_SHIFT        (0)
#define CR_PERIP_SCB0_SYS_CLK_STATUS_MASK         (0x00000001)
#define CR_PERIP_SCB0_SYS_CLK_STATUS_FLAGS        (REG_VOL)
#define CR_PERIP_SCB0_SYS_CLK_STATUS_LENGTH       (1)

/* Field CR_PERIP_SCB1_SYS_CLK_STATUS */
#define CR_PERIP_SCB1_SYS_CLK_STATUS_OFFSET       CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_SCB1_SYS_CLK_STATUS_SHIFT        (1)
#define CR_PERIP_SCB1_SYS_CLK_STATUS_MASK         (0x00000002)
#define CR_PERIP_SCB1_SYS_CLK_STATUS_FLAGS        (REG_VOL)
#define CR_PERIP_SCB1_SYS_CLK_STATUS_LENGTH       (1)

/* Field CR_PERIP_SCB2_SYS_CLK_STATUS */
#define CR_PERIP_SCB2_SYS_CLK_STATUS_OFFSET       CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_SCB2_SYS_CLK_STATUS_SHIFT        (2)
#define CR_PERIP_SCB2_SYS_CLK_STATUS_MASK         (0x00000004)
#define CR_PERIP_SCB2_SYS_CLK_STATUS_FLAGS        (REG_VOL)
#define CR_PERIP_SCB2_SYS_CLK_STATUS_LENGTH       (1)

/* Field CR_PERIP_UART0_SYS_CLK_STATUS */
#define CR_PERIP_UART0_SYS_CLK_STATUS_OFFSET      CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_UART0_SYS_CLK_STATUS_SHIFT       (3)
#define CR_PERIP_UART0_SYS_CLK_STATUS_MASK        (0x00000008)
#define CR_PERIP_UART0_SYS_CLK_STATUS_FLAGS       (REG_VOL)
#define CR_PERIP_UART0_SYS_CLK_STATUS_LENGTH      (1)

/* Field CR_PERIP_UART1_SYS_CLK_STATUS */
#define CR_PERIP_UART1_SYS_CLK_STATUS_OFFSET      CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_UART1_SYS_CLK_STATUS_SHIFT       (4)
#define CR_PERIP_UART1_SYS_CLK_STATUS_MASK        (0x00000010)
#define CR_PERIP_UART1_SYS_CLK_STATUS_FLAGS       (REG_VOL)
#define CR_PERIP_UART1_SYS_CLK_STATUS_LENGTH      (1)

/* Field CR_PERIP_SPIM_SYS_CLK_STATUS */
#define CR_PERIP_SPIM_SYS_CLK_STATUS_OFFSET       CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_SPIM_SYS_CLK_STATUS_SHIFT        (5)
#define CR_PERIP_SPIM_SYS_CLK_STATUS_MASK         (0x00000020)
#define CR_PERIP_SPIM_SYS_CLK_STATUS_FLAGS        (REG_VOL)
#define CR_PERIP_SPIM_SYS_CLK_STATUS_LENGTH       (1)

/* Field CR_PERIP_SPIS_SYS_CLK_STATUS */
#define CR_PERIP_SPIS_SYS_CLK_STATUS_OFFSET       CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_SPIS_SYS_CLK_STATUS_SHIFT        (6)
#define CR_PERIP_SPIS_SYS_CLK_STATUS_MASK         (0x00000040)
#define CR_PERIP_SPIS_SYS_CLK_STATUS_FLAGS        (REG_VOL)
#define CR_PERIP_SPIS_SYS_CLK_STATUS_LENGTH       (1)

/* Field CR_PERIP_SPIM1_SYS_CLK_STATUS */
#define CR_PERIP_SPIM1_SYS_CLK_STATUS_OFFSET      CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_SPIM1_SYS_CLK_STATUS_SHIFT       (7)
#define CR_PERIP_SPIM1_SYS_CLK_STATUS_MASK        (0x00000080)
#define CR_PERIP_SPIM1_SYS_CLK_STATUS_FLAGS       (REG_VOL)
#define CR_PERIP_SPIM1_SYS_CLK_STATUS_LENGTH      (1)

/* Field CR_PERIP_USB_SYS_CLK_STATUS */
#define CR_PERIP_USB_SYS_CLK_STATUS_OFFSET        CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_USB_SYS_CLK_STATUS_SHIFT         (8)
#define CR_PERIP_USB_SYS_CLK_STATUS_MASK          (0x00000100)
#define CR_PERIP_USB_SYS_CLK_STATUS_FLAGS         (REG_VOL)
#define CR_PERIP_USB_SYS_CLK_STATUS_LENGTH        (1)

/* Field CR_PERIP_DMAC_SYS_CLK_STATUS */
#define CR_PERIP_DMAC_SYS_CLK_STATUS_OFFSET       CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_DMAC_SYS_CLK_STATUS_SHIFT        (9)
#define CR_PERIP_DMAC_SYS_CLK_STATUS_MASK         (0x00000200)
#define CR_PERIP_DMAC_SYS_CLK_STATUS_FLAGS        (REG_VOL)
#define CR_PERIP_DMAC_SYS_CLK_STATUS_LENGTH       (1)

/* Field CR_PERIP_DISEQC0_SYS_CLK_STATUS */
#define CR_PERIP_DISEQC0_SYS_CLK_STATUS_OFFSET    CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_DISEQC0_SYS_CLK_STATUS_SHIFT     (10)
#define CR_PERIP_DISEQC0_SYS_CLK_STATUS_MASK      (0x00000400)
#define CR_PERIP_DISEQC0_SYS_CLK_STATUS_FLAGS     (REG_VOL)
#define CR_PERIP_DISEQC0_SYS_CLK_STATUS_LENGTH    (1)

/* Field CR_PERIP_DISEQC1_SYS_CLK_STATUS */
#define CR_PERIP_DISEQC1_SYS_CLK_STATUS_OFFSET    CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_DISEQC1_SYS_CLK_STATUS_SHIFT     (11)
#define CR_PERIP_DISEQC1_SYS_CLK_STATUS_MASK      (0x00000800)
#define CR_PERIP_DISEQC1_SYS_CLK_STATUS_FLAGS     (REG_VOL)
#define CR_PERIP_DISEQC1_SYS_CLK_STATUS_LENGTH    (1)

/* Complete Register Definition */
#define CR_PERIP_CLKSTATUS_REG_OFFSET             CR_PERIP_CLKSTATUS_OFFSET
#define CR_PERIP_CLKSTATUS_REG_SHIFT              (0)
#define CR_PERIP_CLKSTATUS_REG_MASK               (0xFFFFFFFF)
#define CR_PERIP_CLKSTATUS_REG_FLAGS              (REG_VOL)
#define CR_PERIP_CLKSTATUS_REG_LENGTH             (32)


/* -------------------- Register CR_PERIP_DMA_ROUTE_SEL -------------------- */

#define CR_PERIP_DMA_ROUTE_SEL_OFFSET             (0x0080)

/* Field CR_PERIP_DMA_SEL_3 */
#define CR_PERIP_DMA_SEL_3_OFFSET                 CR_PERIP_DMA_ROUTE_SEL_OFFSET
#define CR_PERIP_DMA_SEL_3_SHIFT                  (12)
#define CR_PERIP_DMA_SEL_3_MASK                   (0x0000F000)
#define CR_PERIP_DMA_SEL_3_FLAGS                  (REG_VOL)
#define CR_PERIP_DMA_SEL_3_LENGTH                 (4)

/* Field CR_PERIP_DMA_SEL_2 */
#define CR_PERIP_DMA_SEL_2_OFFSET                 CR_PERIP_DMA_ROUTE_SEL_OFFSET
#define CR_PERIP_DMA_SEL_2_SHIFT                  (8)
#define CR_PERIP_DMA_SEL_2_MASK                   (0x00000F00)
#define CR_PERIP_DMA_SEL_2_FLAGS                  (REG_VOL)
#define CR_PERIP_DMA_SEL_2_LENGTH                 (4)

/* Field CR_PERIP_DMA_SEL_1 */
#define CR_PERIP_DMA_SEL_1_OFFSET                 CR_PERIP_DMA_ROUTE_SEL_OFFSET
#define CR_PERIP_DMA_SEL_1_SHIFT                  (4)
#define CR_PERIP_DMA_SEL_1_MASK                   (0x000000F0)
#define CR_PERIP_DMA_SEL_1_FLAGS                  (REG_VOL)
#define CR_PERIP_DMA_SEL_1_LENGTH                 (4)

/* Field CR_PERIP_DMA_SEL_0 */
#define CR_PERIP_DMA_SEL_0_OFFSET                 CR_PERIP_DMA_ROUTE_SEL_OFFSET
#define CR_PERIP_DMA_SEL_0_SHIFT                  (0)
#define CR_PERIP_DMA_SEL_0_MASK                   (0x0000000F)
#define CR_PERIP_DMA_SEL_0_FLAGS                  (REG_VOL)
#define CR_PERIP_DMA_SEL_0_LENGTH                 (4)

/* Complete Register Definition */
#define CR_PERIP_DMA_ROUTE_SEL_REG_OFFSET         CR_PERIP_DMA_ROUTE_SEL_OFFSET
#define CR_PERIP_DMA_ROUTE_SEL_REG_SHIFT          (0)
#define CR_PERIP_DMA_ROUTE_SEL_REG_MASK           (0xFFFFFFFF)
#define CR_PERIP_DMA_ROUTE_SEL_REG_FLAGS          (REG_VOL)
#define CR_PERIP_DMA_ROUTE_SEL_REG_LENGTH         (32)


/* -------------------- Register CR_PERIP_WAKE_EN -------------------- */

#define CR_PERIP_WAKE_EN_OFFSET                   (0x00C0)

/* Field CR_PERIP_WAKE_EN */
/*#define CR_PERIP_WAKE_EN_OFFSET                 CR_PERIP_WAKE_EN_OFFSET*/
#define CR_PERIP_WAKE_EN_SHIFT                    (0)
#define CR_PERIP_WAKE_EN_MASK                     (0xFFFFFFFF)
#define CR_PERIP_WAKE_EN_FLAGS                    (REG_VOL)
#define CR_PERIP_WAKE_EN_LENGTH                   (32)

/* Complete Register Definition */
#define CR_PERIP_WAKE_EN_REG_OFFSET               CR_PERIP_WAKE_EN_OFFSET
#define CR_PERIP_WAKE_EN_REG_SHIFT                (0)
#define CR_PERIP_WAKE_EN_REG_MASK                 (0xFFFFFFFF)
#define CR_PERIP_WAKE_EN_REG_FLAGS                (REG_VOL)
#define CR_PERIP_WAKE_EN_REG_LENGTH               (32)


/* -------------------- Register CR_PERIP_PDM_CONTROL -------------------- */

#define CR_PERIP_PDM_CONTROL_OFFSET               (0x01C0)

/* Field CR_PERIP_PDM_CONTROL */
/*#define CR_PERIP_PDM_CONTROL_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET*/
#define CR_PERIP_PDM_CONTROL_SHIFT                (0)
#define CR_PERIP_PDM_CONTROL_MASK                 (0x0000000F)
#define CR_PERIP_PDM_CONTROL_FLAGS                (REG_VOL)
#define CR_PERIP_PDM_CONTROL_LENGTH               (4)

/* Field CR_PERIP_PDM_SYM_UP0_A */
#define CR_PERIP_PDM_SYM_UP0_A_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_SYM_UP0_A_SHIFT              (8)
#define CR_PERIP_PDM_SYM_UP0_A_MASK               (0x00000100)
#define CR_PERIP_PDM_SYM_UP0_A_FLAGS              (REG_VOL)
#define CR_PERIP_PDM_SYM_UP0_A_LENGTH             (1)

/* Field CR_PERIP_PDM_SYM_UP0_B */
#define CR_PERIP_PDM_SYM_UP0_B_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_SYM_UP0_B_SHIFT              (9)
#define CR_PERIP_PDM_SYM_UP0_B_MASK               (0x00000200)
#define CR_PERIP_PDM_SYM_UP0_B_FLAGS              (REG_VOL)
#define CR_PERIP_PDM_SYM_UP0_B_LENGTH             (1)

/* Field CR_PERIP_PDM_SYM_UP0_C */
#define CR_PERIP_PDM_SYM_UP0_C_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_SYM_UP0_C_SHIFT              (10)
#define CR_PERIP_PDM_SYM_UP0_C_MASK               (0x00000400)
#define CR_PERIP_PDM_SYM_UP0_C_FLAGS              (REG_VOL)
#define CR_PERIP_PDM_SYM_UP0_C_LENGTH             (1)

/* Field CR_PERIP_PDM_SYM_UP0_D */
#define CR_PERIP_PDM_SYM_UP0_D_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_SYM_UP0_D_SHIFT              (11)
#define CR_PERIP_PDM_SYM_UP0_D_MASK               (0x00000800)
#define CR_PERIP_PDM_SYM_UP0_D_FLAGS              (REG_VOL)
#define CR_PERIP_PDM_SYM_UP0_D_LENGTH             (1)

/* Field CR_PERIP_PDM_SYM_UP1_A */
#define CR_PERIP_PDM_SYM_UP1_A_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_SYM_UP1_A_SHIFT              (12)
#define CR_PERIP_PDM_SYM_UP1_A_MASK               (0x00001000)
#define CR_PERIP_PDM_SYM_UP1_A_FLAGS              (REG_VOL)
#define CR_PERIP_PDM_SYM_UP1_A_LENGTH             (1)

/* Field CR_PERIP_PDM_SYM_UP1_B */
#define CR_PERIP_PDM_SYM_UP1_B_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_SYM_UP1_B_SHIFT              (13)
#define CR_PERIP_PDM_SYM_UP1_B_MASK               (0x00002000)
#define CR_PERIP_PDM_SYM_UP1_B_FLAGS              (REG_VOL)
#define CR_PERIP_PDM_SYM_UP1_B_LENGTH             (1)

/* Field CR_PERIP_PDM_SYM_UP1_C */
#define CR_PERIP_PDM_SYM_UP1_C_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_SYM_UP1_C_SHIFT              (14)
#define CR_PERIP_PDM_SYM_UP1_C_MASK               (0x00004000)
#define CR_PERIP_PDM_SYM_UP1_C_FLAGS              (REG_VOL)
#define CR_PERIP_PDM_SYM_UP1_C_LENGTH             (1)

/* Field CR_PERIP_PDM_SYM_UP1_D */
#define CR_PERIP_PDM_SYM_UP1_D_OFFSET             CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_SYM_UP1_D_SHIFT              (15)
#define CR_PERIP_PDM_SYM_UP1_D_MASK               (0x00008000)
#define CR_PERIP_PDM_SYM_UP1_D_FLAGS              (REG_VOL)
#define CR_PERIP_PDM_SYM_UP1_D_LENGTH             (1)

/* Complete Register Definition */
#define CR_PERIP_PDM_CONTROL_REG_OFFSET           CR_PERIP_PDM_CONTROL_OFFSET
#define CR_PERIP_PDM_CONTROL_REG_SHIFT            (0)
#define CR_PERIP_PDM_CONTROL_REG_MASK             (0xFFFFFFFF)
#define CR_PERIP_PDM_CONTROL_REG_FLAGS            (REG_VOL)
#define CR_PERIP_PDM_CONTROL_REG_LENGTH           (32)


/* -------------------- Register CR_PERIP_PDM_SELECT -------------------- */

#define CR_PERIP_PDM_SELECT_OFFSET                (0x01C4)

/* Field CR_PERIP_PDM_A_SEL */
#define CR_PERIP_PDM_A_SEL_OFFSET                 CR_PERIP_PDM_SELECT_OFFSET
#define CR_PERIP_PDM_A_SEL_SHIFT                  (0)
#define CR_PERIP_PDM_A_SEL_MASK                   (0x00000003)
#define CR_PERIP_PDM_A_SEL_FLAGS                  (REG_VOL)
#define CR_PERIP_PDM_A_SEL_LENGTH                 (2)

/* Field CR_PERIP_PDM_B_SEL */
#define CR_PERIP_PDM_B_SEL_OFFSET                 CR_PERIP_PDM_SELECT_OFFSET
#define CR_PERIP_PDM_B_SEL_SHIFT                  (4)
#define CR_PERIP_PDM_B_SEL_MASK                   (0x00000030)
#define CR_PERIP_PDM_B_SEL_FLAGS                  (REG_VOL)
#define CR_PERIP_PDM_B_SEL_LENGTH                 (2)

/* Field CR_PERIP_PDM_C_SEL */
#define CR_PERIP_PDM_C_SEL_OFFSET                 CR_PERIP_PDM_SELECT_OFFSET
#define CR_PERIP_PDM_C_SEL_SHIFT                  (8)
#define CR_PERIP_PDM_C_SEL_MASK                   (0x00000300)
#define CR_PERIP_PDM_C_SEL_FLAGS                  (REG_VOL)
#define CR_PERIP_PDM_C_SEL_LENGTH                 (2)

/* Field CR_PERIP_PDM_D_SEL */
#define CR_PERIP_PDM_D_SEL_OFFSET                 CR_PERIP_PDM_SELECT_OFFSET
#define CR_PERIP_PDM_D_SEL_SHIFT                  (12)
#define CR_PERIP_PDM_D_SEL_MASK                   (0x00003000)
#define CR_PERIP_PDM_D_SEL_FLAGS                  (REG_VOL)
#define CR_PERIP_PDM_D_SEL_LENGTH                 (2)

/* Complete Register Definition */
#define CR_PERIP_PDM_SELECT_REG_OFFSET            CR_PERIP_PDM_SELECT_OFFSET
#define CR_PERIP_PDM_SELECT_REG_SHIFT             (0)
#define CR_PERIP_PDM_SELECT_REG_MASK              (0xFFFFFFFF)
#define CR_PERIP_PDM_SELECT_REG_FLAGS             (REG_VOL)
#define CR_PERIP_PDM_SELECT_REG_LENGTH            (32)


/* -------------------- Register CR_PERIP_SPI_CTRL -------------------- */

#define CR_PERIP_SPI_CTRL_OFFSET                  (0x01D0)

/* Field CR_PERIP_SPI_SLAVE_EN */
#define CR_PERIP_SPI_SLAVE_EN_OFFSET              CR_PERIP_SPI_CTRL_OFFSET
#define CR_PERIP_SPI_SLAVE_EN_SHIFT               (0)
#define CR_PERIP_SPI_SLAVE_EN_MASK                (0x00000001)
#define CR_PERIP_SPI_SLAVE_EN_FLAGS               (REG_VOL)
#define CR_PERIP_SPI_SLAVE_EN_LENGTH              (1)

/* Field CR_PERIP_SPI_CLK_OUTPUT */
#define CR_PERIP_SPI_CLK_OUTPUT_OFFSET            CR_PERIP_SPI_CTRL_OFFSET
#define CR_PERIP_SPI_CLK_OUTPUT_SHIFT             (1)
#define CR_PERIP_SPI_CLK_OUTPUT_MASK              (0x00000002)
#define CR_PERIP_SPI_CLK_OUTPUT_FLAGS             (REG_VOL)
#define CR_PERIP_SPI_CLK_OUTPUT_LENGTH            (1)

/* Field CR_PERIP_SPI_LBACK */
#define CR_PERIP_SPI_LBACK_OFFSET                 CR_PERIP_SPI_CTRL_OFFSET
#define CR_PERIP_SPI_LBACK_SHIFT                  (4)
#define CR_PERIP_SPI_LBACK_MASK                   (0x00000010)
#define CR_PERIP_SPI_LBACK_FLAGS                  (REG_VOL)
#define CR_PERIP_SPI_LBACK_LENGTH                 (1)

/* Complete Register Definition */
#define CR_PERIP_SPI_CTRL_REG_OFFSET              CR_PERIP_SPI_CTRL_OFFSET
#define CR_PERIP_SPI_CTRL_REG_SHIFT               (0)
#define CR_PERIP_SPI_CTRL_REG_MASK                (0xFFFFFFFF)
#define CR_PERIP_SPI_CTRL_REG_FLAGS               (REG_VOL)
#define CR_PERIP_SPI_CTRL_REG_LENGTH              (32)


/* -------------------- Register CR_PERIP_SOCIF_CTRL -------------------- */

#define CR_PERIP_SOCIF_CTRL_OFFSET                (0x01E0)

/* Field CR_PERIP_SOCIF_FLUSH */
#define CR_PERIP_SOCIF_FLUSH_OFFSET               CR_PERIP_SOCIF_CTRL_OFFSET
#define CR_PERIP_SOCIF_FLUSH_SHIFT                (0)
#define CR_PERIP_SOCIF_FLUSH_MASK                 (0x00000001)
#define CR_PERIP_SOCIF_FLUSH_FLAGS                (REG_VOL)
#define CR_PERIP_SOCIF_FLUSH_LENGTH               (1)

/* Complete Register Definition */
#define CR_PERIP_SOCIF_CTRL_REG_OFFSET            CR_PERIP_SOCIF_CTRL_OFFSET
#define CR_PERIP_SOCIF_CTRL_REG_SHIFT             (0)
#define CR_PERIP_SOCIF_CTRL_REG_MASK              (0xFFFFFFFF)
#define CR_PERIP_SOCIF_CTRL_REG_FLAGS             (REG_VOL)
#define CR_PERIP_SOCIF_CTRL_REG_LENGTH            (32)


/* -------------------- Register CR_PERIP_SOCIF_STATUS -------------------- */

#define CR_PERIP_SOCIF_STATUS_OFFSET              (0x01E4)

/* Field CR_PERIP_SOCIF_FIFO_STATUS */
#define CR_PERIP_SOCIF_FIFO_STATUS_OFFSET         CR_PERIP_SOCIF_STATUS_OFFSET
#define CR_PERIP_SOCIF_FIFO_STATUS_SHIFT          (0)
#define CR_PERIP_SOCIF_FIFO_STATUS_MASK           (0x0000000F)
#define CR_PERIP_SOCIF_FIFO_STATUS_FLAGS          (REG_VOL)
#define CR_PERIP_SOCIF_FIFO_STATUS_LENGTH         (4)

/* Complete Register Definition */
#define CR_PERIP_SOCIF_STATUS_REG_OFFSET          CR_PERIP_SOCIF_STATUS_OFFSET
#define CR_PERIP_SOCIF_STATUS_REG_SHIFT           (0)
#define CR_PERIP_SOCIF_STATUS_REG_MASK            (0xFFFFFFFF)
#define CR_PERIP_SOCIF_STATUS_REG_FLAGS           (REG_VOL)
#define CR_PERIP_SOCIF_STATUS_REG_LENGTH          (32)


/* -------------------- Register CR_PERIP_USB_PHY_CONTROL -------------------- */

#define CR_PERIP_USB_PHY_CONTROL_OFFSET           (0x0200)

/* Field CR_PERIP_USB_OTGDISABLE */
#define CR_PERIP_USB_OTGDISABLE_OFFSET            CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_USB_OTGDISABLE_SHIFT             (12)
#define CR_PERIP_USB_OTGDISABLE_MASK              (0x00001000)
#define CR_PERIP_USB_OTGDISABLE_FLAGS             (REG_VOL)
#define CR_PERIP_USB_OTGDISABLE_LENGTH            (1)

/* Field CR_PERIP_USB_LOOPBACKEN */
#define CR_PERIP_USB_LOOPBACKEN_OFFSET            CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_USB_LOOPBACKEN_SHIFT             (16)
#define CR_PERIP_USB_LOOPBACKEN_MASK              (0x00010000)
#define CR_PERIP_USB_LOOPBACKEN_FLAGS             (REG_VOL)
#define CR_PERIP_USB_LOOPBACKEN_LENGTH            (1)

/* Field CR_PERIP_UTMI_DPPULLDOWN */
#define CR_PERIP_UTMI_DPPULLDOWN_OFFSET           CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_UTMI_DPPULLDOWN_SHIFT            (20)
#define CR_PERIP_UTMI_DPPULLDOWN_MASK             (0x00100000)
#define CR_PERIP_UTMI_DPPULLDOWN_FLAGS            (REG_VOL)
#define CR_PERIP_UTMI_DPPULLDOWN_LENGTH           (1)

/* Field CR_PERIP_UTMI_DMPULLDOWN */
#define CR_PERIP_UTMI_DMPULLDOWN_OFFSET           CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_UTMI_DMPULLDOWN_SHIFT            (24)
#define CR_PERIP_UTMI_DMPULLDOWN_MASK             (0x01000000)
#define CR_PERIP_UTMI_DMPULLDOWN_FLAGS            (REG_VOL)
#define CR_PERIP_UTMI_DMPULLDOWN_LENGTH           (1)

/* Field CR_PERIP_UTMI_PULLEN */
#define CR_PERIP_UTMI_PULLEN_OFFSET               CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_UTMI_PULLEN_SHIFT                (27)
#define CR_PERIP_UTMI_PULLEN_MASK                 (0x08000000)
#define CR_PERIP_UTMI_PULLEN_FLAGS                (REG_VOL)
#define CR_PERIP_UTMI_PULLEN_LENGTH               (1)

/* Field CR_PERIP_USB_TXBITSTUFFEN */
#define CR_PERIP_USB_TXBITSTUFFEN_OFFSET          CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_USB_TXBITSTUFFEN_SHIFT           (28)
#define CR_PERIP_USB_TXBITSTUFFEN_MASK            (0x10000000)
#define CR_PERIP_USB_TXBITSTUFFEN_FLAGS           (REG_VOL)
#define CR_PERIP_USB_TXBITSTUFFEN_LENGTH          (1)

/* Field CR_PERIP_USB_TXBITSTUFFENH */
#define CR_PERIP_USB_TXBITSTUFFENH_OFFSET         CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_USB_TXBITSTUFFENH_SHIFT          (29)
#define CR_PERIP_USB_TXBITSTUFFENH_MASK           (0x20000000)
#define CR_PERIP_USB_TXBITSTUFFENH_FLAGS          (REG_VOL)
#define CR_PERIP_USB_TXBITSTUFFENH_LENGTH         (1)

/* Field CR_PERIP_USB_COMMONONN */
#define CR_PERIP_USB_COMMONONN_OFFSET             CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_USB_COMMONONN_SHIFT              (31)
#define CR_PERIP_USB_COMMONONN_MASK               (0x80000000)
#define CR_PERIP_USB_COMMONONN_FLAGS              (REG_VOL)
#define CR_PERIP_USB_COMMONONN_LENGTH             (1)

/* Complete Register Definition */
#define CR_PERIP_USB_PHY_CONTROL_REG_OFFSET       CR_PERIP_USB_PHY_CONTROL_OFFSET
#define CR_PERIP_USB_PHY_CONTROL_REG_SHIFT        (0)
#define CR_PERIP_USB_PHY_CONTROL_REG_MASK         (0xFFFFFFFF)
#define CR_PERIP_USB_PHY_CONTROL_REG_FLAGS        (REG_VOL)
#define CR_PERIP_USB_PHY_CONTROL_REG_LENGTH       (32)


/* -------------------- Register CR_PERIP_USB_PHY_TUNE_CONTROL -------------------- */

#define CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET      (0x0204)

/* Field CR_PERIP_USB_OTGTUNE */
#define CR_PERIP_USB_OTGTUNE_OFFSET               CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_OTGTUNE_SHIFT                (0)
#define CR_PERIP_USB_OTGTUNE_MASK                 (0x00000007)
#define CR_PERIP_USB_OTGTUNE_FLAGS                (REG_VOL)
#define CR_PERIP_USB_OTGTUNE_LENGTH               (3)

/* Field CR_PERIP_USB_COMPDISTUNE */
#define CR_PERIP_USB_COMPDISTUNE_OFFSET           CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_COMPDISTUNE_SHIFT            (4)
#define CR_PERIP_USB_COMPDISTUNE_MASK             (0x00000070)
#define CR_PERIP_USB_COMPDISTUNE_FLAGS            (REG_VOL)
#define CR_PERIP_USB_COMPDISTUNE_LENGTH           (3)

/* Field CR_PERIP_USB_SQRXTUNE */
#define CR_PERIP_USB_SQRXTUNE_OFFSET              CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_SQRXTUNE_SHIFT               (8)
#define CR_PERIP_USB_SQRXTUNE_MASK                (0x00000700)
#define CR_PERIP_USB_SQRXTUNE_FLAGS               (REG_VOL)
#define CR_PERIP_USB_SQRXTUNE_LENGTH              (3)

/* Field CR_PERIP_USB_TXFSLSTUNE */
#define CR_PERIP_USB_TXFSLSTUNE_OFFSET            CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_TXFSLSTUNE_SHIFT             (12)
#define CR_PERIP_USB_TXFSLSTUNE_MASK              (0x0000F000)
#define CR_PERIP_USB_TXFSLSTUNE_FLAGS             (REG_VOL)
#define CR_PERIP_USB_TXFSLSTUNE_LENGTH            (4)

/* Field CR_PERIP_USB_TXVREFTUNE */
#define CR_PERIP_USB_TXVREFTUNE_OFFSET            CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_TXVREFTUNE_SHIFT             (16)
#define CR_PERIP_USB_TXVREFTUNE_MASK              (0x000F0000)
#define CR_PERIP_USB_TXVREFTUNE_FLAGS             (REG_VOL)
#define CR_PERIP_USB_TXVREFTUNE_LENGTH            (4)

/* Field CR_PERIP_USB_TXRISETUNE */
#define CR_PERIP_USB_TXRISETUNE_OFFSET            CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_TXRISETUNE_SHIFT             (20)
#define CR_PERIP_USB_TXRISETUNE_MASK              (0x00100000)
#define CR_PERIP_USB_TXRISETUNE_FLAGS             (REG_VOL)
#define CR_PERIP_USB_TXRISETUNE_LENGTH            (1)

/* Field CR_PERIP_USB_TXPREEMPHASISTUNE */
#define CR_PERIP_USB_TXPREEMPHASISTUNE_OFFSET     CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_TXPREEMPHASISTUNE_SHIFT      (24)
#define CR_PERIP_USB_TXPREEMPHASISTUNE_MASK       (0x01000000)
#define CR_PERIP_USB_TXPREEMPHASISTUNE_FLAGS      (REG_VOL)
#define CR_PERIP_USB_TXPREEMPHASISTUNE_LENGTH     (1)

/* Field CR_PERIP_USB_VMT_VBUSVALID */
#define CR_PERIP_USB_VMT_VBUSVALID_OFFSET         CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_VMT_VBUSVALID_SHIFT          (28)
#define CR_PERIP_USB_VMT_VBUSVALID_MASK           (0x10000000)
#define CR_PERIP_USB_VMT_VBUSVALID_FLAGS          (REG_VOL)
#define CR_PERIP_USB_VMT_VBUSVALID_LENGTH         (1)

/* Field CR_PERIP_USB_TXHSXVTUNE */
#define CR_PERIP_USB_TXHSXVTUNE_OFFSET            CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_TXHSXVTUNE_SHIFT             (30)
#define CR_PERIP_USB_TXHSXVTUNE_MASK              (0xC0000000)
#define CR_PERIP_USB_TXHSXVTUNE_FLAGS             (REG_VOL)
#define CR_PERIP_USB_TXHSXVTUNE_LENGTH            (2)

/* Complete Register Definition */
#define CR_PERIP_USB_PHY_TUNE_CONTROL_REG_OFFSET  CR_PERIP_USB_PHY_TUNE_CONTROL_OFFSET
#define CR_PERIP_USB_PHY_TUNE_CONTROL_REG_SHIFT   (0)
#define CR_PERIP_USB_PHY_TUNE_CONTROL_REG_MASK    (0xFFFFFFFF)
#define CR_PERIP_USB_PHY_TUNE_CONTROL_REG_FLAGS   (REG_VOL)
#define CR_PERIP_USB_PHY_TUNE_CONTROL_REG_LENGTH  (32)


/* -------------------- Register CR_PERIP_USB_PHY_STRAP_CONTROL -------------------- */

#define CR_PERIP_USB_PHY_STRAP_CONTROL_OFFSET     (0x0208)

/* Field CR_PERIP_USB_REFCLKDIV */
#define CR_PERIP_USB_REFCLKDIV_OFFSET             CR_PERIP_USB_PHY_STRAP_CONTROL_OFFSET
#define CR_PERIP_USB_REFCLKDIV_SHIFT              (0)
#define CR_PERIP_USB_REFCLKDIV_MASK               (0x00000003)
#define CR_PERIP_USB_REFCLKDIV_FLAGS              (REG_VOL)
#define CR_PERIP_USB_REFCLKDIV_LENGTH             (2)

/* Field CR_PERIP_USB_REFCLKSEL */
#define CR_PERIP_USB_REFCLKSEL_OFFSET             CR_PERIP_USB_PHY_STRAP_CONTROL_OFFSET
#define CR_PERIP_USB_REFCLKSEL_SHIFT              (4)
#define CR_PERIP_USB_REFCLKSEL_MASK               (0x00000030)
#define CR_PERIP_USB_REFCLKSEL_FLAGS              (REG_VOL)
#define CR_PERIP_USB_REFCLKSEL_LENGTH             (2)

/* Field CR_PERIP_USB_VBUS_VLDEXT_SEL */
#define CR_PERIP_USB_VBUS_VLDEXT_SEL_OFFSET       CR_PERIP_USB_PHY_STRAP_CONTROL_OFFSET
#define CR_PERIP_USB_VBUS_VLDEXT_SEL_SHIFT        (8)
#define CR_PERIP_USB_VBUS_VLDEXT_SEL_MASK         (0x00000100)
#define CR_PERIP_USB_VBUS_VLDEXT_SEL_FLAGS        (REG_VOL)
#define CR_PERIP_USB_VBUS_VLDEXT_SEL_LENGTH       (1)

/* Field CR_PERIP_USB_ISO_PHY */
#define CR_PERIP_USB_ISO_PHY_OFFSET               CR_PERIP_USB_PHY_STRAP_CONTROL_OFFSET
#define CR_PERIP_USB_ISO_PHY_SHIFT                (12)
#define CR_PERIP_USB_ISO_PHY_MASK                 (0x00001000)
#define CR_PERIP_USB_ISO_PHY_FLAGS                (REG_VOL)
#define CR_PERIP_USB_ISO_PHY_LENGTH               (1)

/* Field CR_PERIP_USB_SLEEPM */
#define CR_PERIP_USB_SLEEPM_OFFSET                CR_PERIP_USB_PHY_STRAP_CONTROL_OFFSET
#define CR_PERIP_USB_SLEEPM_SHIFT                 (16)
#define CR_PERIP_USB_SLEEPM_MASK                  (0x00010000)
#define CR_PERIP_USB_SLEEPM_FLAGS                 (REG_VOL)
#define CR_PERIP_USB_SLEEPM_LENGTH                (1)

/* Field CR_PERIP_USB_FIFO_SLV_AD */
#define CR_PERIP_USB_FIFO_SLV_AD_OFFSET           CR_PERIP_USB_PHY_STRAP_CONTROL_OFFSET
#define CR_PERIP_USB_FIFO_SLV_AD_SHIFT            (20)
#define CR_PERIP_USB_FIFO_SLV_AD_MASK             (0x00F00000)
#define CR_PERIP_USB_FIFO_SLV_AD_FLAGS            (REG_VOL)
#define CR_PERIP_USB_FIFO_SLV_AD_LENGTH           (4)

/* Complete Register Definition */
#define CR_PERIP_USB_PHY_STRAP_CONTROL_REG_OFFSET CR_PERIP_USB_PHY_STRAP_CONTROL_OFFSET
#define CR_PERIP_USB_PHY_STRAP_CONTROL_REG_SHIFT  (0)
#define CR_PERIP_USB_PHY_STRAP_CONTROL_REG_MASK   (0xFFFFFFFF)
#define CR_PERIP_USB_PHY_STRAP_CONTROL_REG_FLAGS  (REG_VOL)
#define CR_PERIP_USB_PHY_STRAP_CONTROL_REG_LENGTH (32)


/* -------------------- Register CR_PERIP_USB_PHY_STATUS -------------------- */

#define CR_PERIP_USB_PHY_STATUS_OFFSET            (0x020C)

/* Field CR_PERIP_USB_RX_UTMI_CLK */
#define CR_PERIP_USB_RX_UTMI_CLK_OFFSET           CR_PERIP_USB_PHY_STATUS_OFFSET
#define CR_PERIP_USB_RX_UTMI_CLK_SHIFT            (8)
#define CR_PERIP_USB_RX_UTMI_CLK_MASK             (0x00000100)
#define CR_PERIP_USB_RX_UTMI_CLK_FLAGS            (REG_VOL)
#define CR_PERIP_USB_RX_UTMI_CLK_LENGTH           (1)

/* Field CR_PERIP_USB_RX_PHY_CLK */
#define CR_PERIP_USB_RX_PHY_CLK_OFFSET            CR_PERIP_USB_PHY_STATUS_OFFSET
#define CR_PERIP_USB_RX_PHY_CLK_SHIFT             (9)
#define CR_PERIP_USB_RX_PHY_CLK_MASK              (0x00000200)
#define CR_PERIP_USB_RX_PHY_CLK_FLAGS             (REG_VOL)
#define CR_PERIP_USB_RX_PHY_CLK_LENGTH            (1)

/* Complete Register Definition */
#define CR_PERIP_USB_PHY_STATUS_REG_OFFSET        CR_PERIP_USB_PHY_STATUS_OFFSET
#define CR_PERIP_USB_PHY_STATUS_REG_SHIFT         (0)
#define CR_PERIP_USB_PHY_STATUS_REG_MASK          (0xFFFFFFFF)
#define CR_PERIP_USB_PHY_STATUS_REG_FLAGS         (REG_VOL)
#define CR_PERIP_USB_PHY_STATUS_REG_LENGTH        (32)


/* -------------------- Register CR_PERIP_USB_IDS -------------------- */

#define CR_PERIP_USB_IDS_OFFSET                   (0x0218)

/* Field CR_PERIP_USB_VENDOR_ID */
#define CR_PERIP_USB_VENDOR_ID_OFFSET             CR_PERIP_USB_IDS_OFFSET
#define CR_PERIP_USB_VENDOR_ID_SHIFT              (0)
#define CR_PERIP_USB_VENDOR_ID_MASK               (0x0000FFFF)
#define CR_PERIP_USB_VENDOR_ID_FLAGS              (REG_VOL)
#define CR_PERIP_USB_VENDOR_ID_LENGTH             (16)

/* Field CR_PERIP_USB_PRODUCT_ID */
#define CR_PERIP_USB_PRODUCT_ID_OFFSET            CR_PERIP_USB_IDS_OFFSET
#define CR_PERIP_USB_PRODUCT_ID_SHIFT             (16)
#define CR_PERIP_USB_PRODUCT_ID_MASK              (0xFFFF0000)
#define CR_PERIP_USB_PRODUCT_ID_FLAGS             (REG_VOL)
#define CR_PERIP_USB_PRODUCT_ID_LENGTH            (16)

/* Complete Register Definition */
#define CR_PERIP_USB_IDS_REG_OFFSET               CR_PERIP_USB_IDS_OFFSET
#define CR_PERIP_USB_IDS_REG_SHIFT                (0)
#define CR_PERIP_USB_IDS_REG_MASK                 (0xFFFFFFFF)
#define CR_PERIP_USB_IDS_REG_FLAGS                (REG_VOL)
#define CR_PERIP_USB_IDS_REG_LENGTH               (32)


/* -------------------- Register CR_USB_AHB_ERROR_FLAGS -------------------- */

#define CR_USB_AHB_ERROR_FLAGS_OFFSET             (0x0234)

/* Field CR_USB_IMG_TO_AHB_ERROR_FLAG */
#define CR_USB_IMG_TO_AHB_ERROR_FLAG_OFFSET       CR_USB_AHB_ERROR_FLAGS_OFFSET
#define CR_USB_IMG_TO_AHB_ERROR_FLAG_SHIFT        (1)
#define CR_USB_IMG_TO_AHB_ERROR_FLAG_MASK         (0x00000002)
#define CR_USB_IMG_TO_AHB_ERROR_FLAG_FLAGS        (REG_VOL)
#define CR_USB_IMG_TO_AHB_ERROR_FLAG_LENGTH       (1)

/* Field CR_USB_AHB_TO_IMG_ERROR_FLAG */
#define CR_USB_AHB_TO_IMG_ERROR_FLAG_OFFSET       CR_USB_AHB_ERROR_FLAGS_OFFSET
#define CR_USB_AHB_TO_IMG_ERROR_FLAG_SHIFT        (0)
#define CR_USB_AHB_TO_IMG_ERROR_FLAG_MASK         (0x00000001)
#define CR_USB_AHB_TO_IMG_ERROR_FLAG_FLAGS        (REG_VOL)
#define CR_USB_AHB_TO_IMG_ERROR_FLAG_LENGTH       (1)

/* Complete Register Definition */
#define CR_USB_AHB_ERROR_FLAGS_REG_OFFSET         CR_USB_AHB_ERROR_FLAGS_OFFSET
#define CR_USB_AHB_ERROR_FLAGS_REG_SHIFT          (0)
#define CR_USB_AHB_ERROR_FLAGS_REG_MASK           (0xFFFFFFFF)
#define CR_USB_AHB_ERROR_FLAGS_REG_FLAGS          (REG_VOL)
#define CR_USB_AHB_ERROR_FLAGS_REG_LENGTH         (32)


/* -------------------- Register CR_NOTI_ALL_DMA_WRITE -------------------- */

#define CR_NOTI_ALL_DMA_WRITE_OFFSET              (0x0238)

/* Field CR_NOTI_ALL_DMA_WRITE */
/*#define CR_NOTI_ALL_DMA_WRITE_OFFSET            CR_NOTI_ALL_DMA_WRITE_OFFSET*/
#define CR_NOTI_ALL_DMA_WRITE_SHIFT               (0)
#define CR_NOTI_ALL_DMA_WRITE_MASK                (0x00000001)
#define CR_NOTI_ALL_DMA_WRITE_FLAGS               (REG_VOL)
#define CR_NOTI_ALL_DMA_WRITE_LENGTH              (1)

/* Complete Register Definition */
#define CR_NOTI_ALL_DMA_WRITE_REG_OFFSET          CR_NOTI_ALL_DMA_WRITE_OFFSET
#define CR_NOTI_ALL_DMA_WRITE_REG_SHIFT           (0)
#define CR_NOTI_ALL_DMA_WRITE_REG_MASK            (0xFFFFFFFF)
#define CR_NOTI_ALL_DMA_WRITE_REG_FLAGS           (REG_VOL)
#define CR_NOTI_ALL_DMA_WRITE_REG_LENGTH          (32)


/* -------------------- Register CR_REM_MEM_SUP -------------------- */

#define CR_REM_MEM_SUP_OFFSET                     (0x023C)

/* Field CR_REM_MEM_SUP */
/*#define CR_REM_MEM_SUP_OFFSET                   CR_REM_MEM_SUP_OFFSET*/
#define CR_REM_MEM_SUP_SHIFT                      (0)
#define CR_REM_MEM_SUP_MASK                       (0x00000001)
#define CR_REM_MEM_SUP_FLAGS                      (REG_VOL)
#define CR_REM_MEM_SUP_LENGTH                     (1)

/* Complete Register Definition */
#define CR_REM_MEM_SUP_REG_OFFSET                 CR_REM_MEM_SUP_OFFSET
#define CR_REM_MEM_SUP_REG_SHIFT                  (0)
#define CR_REM_MEM_SUP_REG_MASK                   (0xFFFFFFFF)
#define CR_REM_MEM_SUP_REG_FLAGS                  (REG_VOL)
#define CR_REM_MEM_SUP_REG_LENGTH                 (32)


/* -------------------- Register CR_PERIP_RSVD0 -------------------- */

#define CR_PERIP_RSVD0_OFFSET                     (0x0280)

/* Field CR_PERIP_RESERVED0 */
#define CR_PERIP_RESERVED0_OFFSET                 CR_PERIP_RSVD0_OFFSET
#define CR_PERIP_RESERVED0_SHIFT                  (0)
#define CR_PERIP_RESERVED0_MASK                   (0xFFFFFFFF)
#define CR_PERIP_RESERVED0_FLAGS                  (REG_VOL)
#define CR_PERIP_RESERVED0_LENGTH                 (32)

/* Complete Register Definition */
#define CR_PERIP_RSVD0_REG_OFFSET                 CR_PERIP_RSVD0_OFFSET
#define CR_PERIP_RSVD0_REG_SHIFT                  (0)
#define CR_PERIP_RSVD0_REG_MASK                   (0xFFFFFFFF)
#define CR_PERIP_RSVD0_REG_FLAGS                  (REG_VOL)
#define CR_PERIP_RSVD0_REG_LENGTH                 (32)


/* -------------------- Register CR_PERIP_RSVD1 -------------------- */

#define CR_PERIP_RSVD1_OFFSET                     (0x0284)

/* Field CR_PERIP_RESERVED1 */
#define CR_PERIP_RESERVED1_OFFSET                 CR_PERIP_RSVD1_OFFSET
#define CR_PERIP_RESERVED1_SHIFT                  (0)
#define CR_PERIP_RESERVED1_MASK                   (0xFFFFFFFF)
#define CR_PERIP_RESERVED1_FLAGS                  (REG_VOL)
#define CR_PERIP_RESERVED1_LENGTH                 (32)

/* Complete Register Definition */
#define CR_PERIP_RSVD1_REG_OFFSET                 CR_PERIP_RSVD1_OFFSET
#define CR_PERIP_RSVD1_REG_SHIFT                  (0)
#define CR_PERIP_RSVD1_REG_MASK                   (0xFFFFFFFF)
#define CR_PERIP_RSVD1_REG_FLAGS                  (REG_VOL)
#define CR_PERIP_RSVD1_REG_LENGTH                 (32)


/* -------------------- Register CR_TOP_CHIP_ID_0 -------------------- */

#define CR_TOP_CHIP_ID_0_OFFSET                   (0x02A0)

/* Field CR_TOP_CHIP_ID_0 */
/*#define CR_TOP_CHIP_ID_0_OFFSET                 CR_TOP_CHIP_ID_0_OFFSET*/
#define CR_TOP_CHIP_ID_0_SHIFT                    (0)
#define CR_TOP_CHIP_ID_0_MASK                     (0xFFFFFFFF)
#define CR_TOP_CHIP_ID_0_FLAGS                    (REG_VOL)
#define CR_TOP_CHIP_ID_0_LENGTH                   (32)

/* Complete Register Definition */
#define CR_TOP_CHIP_ID_0_REG_OFFSET               CR_TOP_CHIP_ID_0_OFFSET
#define CR_TOP_CHIP_ID_0_REG_SHIFT                (0)
#define CR_TOP_CHIP_ID_0_REG_MASK                 (0xFFFFFFFF)
#define CR_TOP_CHIP_ID_0_REG_FLAGS                (REG_VOL)
#define CR_TOP_CHIP_ID_0_REG_LENGTH               (32)


/* -------------------- Register CR_TOP_CHIP_ID_1 -------------------- */

#define CR_TOP_CHIP_ID_1_OFFSET                   (0x02A4)

/* Field CR_TOP_CHIP_ID_1 */
/*#define CR_TOP_CHIP_ID_1_OFFSET                 CR_TOP_CHIP_ID_1_OFFSET*/
#define CR_TOP_CHIP_ID_1_SHIFT                    (0)
#define CR_TOP_CHIP_ID_1_MASK                     (0xFFFFFFFF)
#define CR_TOP_CHIP_ID_1_FLAGS                    (REG_VOL)
#define CR_TOP_CHIP_ID_1_LENGTH                   (32)

/* Complete Register Definition */
#define CR_TOP_CHIP_ID_1_REG_OFFSET               CR_TOP_CHIP_ID_1_OFFSET
#define CR_TOP_CHIP_ID_1_REG_SHIFT                (0)
#define CR_TOP_CHIP_ID_1_REG_MASK                 (0xFFFFFFFF)
#define CR_TOP_CHIP_ID_1_REG_FLAGS                (REG_VOL)
#define CR_TOP_CHIP_ID_1_REG_LENGTH               (32)


/* -------------------- Register CR_TOP_CHIP_ID_2 -------------------- */

#define CR_TOP_CHIP_ID_2_OFFSET                   (0x02A8)

/* Field CR_TOP_CHIP_ID_2 */
/*#define CR_TOP_CHIP_ID_2_OFFSET                 CR_TOP_CHIP_ID_2_OFFSET*/
#define CR_TOP_CHIP_ID_2_SHIFT                    (0)
#define CR_TOP_CHIP_ID_2_MASK                     (0xFFFFFFFF)
#define CR_TOP_CHIP_ID_2_FLAGS                    (REG_VOL)
#define CR_TOP_CHIP_ID_2_LENGTH                   (32)

/* Complete Register Definition */
#define CR_TOP_CHIP_ID_2_REG_OFFSET               CR_TOP_CHIP_ID_2_OFFSET
#define CR_TOP_CHIP_ID_2_REG_SHIFT                (0)
#define CR_TOP_CHIP_ID_2_REG_MASK                 (0xFFFFFFFF)
#define CR_TOP_CHIP_ID_2_REG_FLAGS                (REG_VOL)
#define CR_TOP_CHIP_ID_2_REG_LENGTH               (32)


/* -------------------- Register CR_TOP_CHIP_ID_3 -------------------- */

#define CR_TOP_CHIP_ID_3_OFFSET                   (0x02AC)

/* Field CR_TOP_CHIP_ID_3 */
/*#define CR_TOP_CHIP_ID_3_OFFSET                 CR_TOP_CHIP_ID_3_OFFSET*/
#define CR_TOP_CHIP_ID_3_SHIFT                    (0)
#define CR_TOP_CHIP_ID_3_MASK                     (0xFFFFFFFF)
#define CR_TOP_CHIP_ID_3_FLAGS                    (REG_VOL)
#define CR_TOP_CHIP_ID_3_LENGTH                   (32)

/* Complete Register Definition */
#define CR_TOP_CHIP_ID_3_REG_OFFSET               CR_TOP_CHIP_ID_3_OFFSET
#define CR_TOP_CHIP_ID_3_REG_SHIFT                (0)
#define CR_TOP_CHIP_ID_3_REG_MASK                 (0xFFFFFFFF)
#define CR_TOP_CHIP_ID_3_REG_FLAGS                (REG_VOL)
#define CR_TOP_CHIP_ID_3_REG_LENGTH               (32)


/* -------------------- Register CR_TOP_ECO -------------------- */

#define CR_TOP_ECO_OFFSET                         (0x02B0)

/* Field CR_TOP_ECO_CTRL */
#define CR_TOP_ECO_CTRL_OFFSET                    CR_TOP_ECO_OFFSET
#define CR_TOP_ECO_CTRL_SHIFT                     (0)
#define CR_TOP_ECO_CTRL_MASK                      (0xFFFFFFFF)
#define CR_TOP_ECO_CTRL_FLAGS                     (REG_VOL)
#define CR_TOP_ECO_CTRL_LENGTH                    (32)

/* Complete Register Definition */
#define CR_TOP_ECO_REG_OFFSET                     CR_TOP_ECO_OFFSET
#define CR_TOP_ECO_REG_SHIFT                      (0)
#define CR_TOP_ECO_REG_MASK                       (0xFFFFFFFF)
#define CR_TOP_ECO_REG_FLAGS                      (REG_VOL)
#define CR_TOP_ECO_REG_LENGTH                     (32)


/* -------------------- Register CR_SATURN_CORE_ID -------------------- */

#define CR_SATURN_CORE_ID_OFFSET                  (0x02C0)

/* Field CR_SATURN_CORE_CONFIG */
#define CR_SATURN_CORE_CONFIG_OFFSET              CR_SATURN_CORE_ID_OFFSET
#define CR_SATURN_CORE_CONFIG_SHIFT               (0)
#define CR_SATURN_CORE_CONFIG_MASK                (0x0000FFFF)
#define CR_SATURN_CORE_CONFIG_FLAGS               (REG_VOL)
#define CR_SATURN_CORE_CONFIG_LENGTH              (16)

/* Field CR_SATURN_CORE_ID */
/*#define CR_SATURN_CORE_ID_OFFSET                CR_SATURN_CORE_ID_OFFSET*/
#define CR_SATURN_CORE_ID_SHIFT                   (16)
#define CR_SATURN_CORE_ID_MASK                    (0x00FF0000)
#define CR_SATURN_CORE_ID_FLAGS                   (REG_VOL)
#define CR_SATURN_CORE_ID_LENGTH                  (8)

/* Complete Register Definition */
#define CR_SATURN_CORE_ID_REG_OFFSET              CR_SATURN_CORE_ID_OFFSET
#define CR_SATURN_CORE_ID_REG_SHIFT               (0)
#define CR_SATURN_CORE_ID_REG_MASK                (0xFFFFFFFF)
#define CR_SATURN_CORE_ID_REG_FLAGS               (REG_VOL)
#define CR_SATURN_CORE_ID_REG_LENGTH              (32)


/* -------------------- Register CR_SATURN_CORE_REV -------------------- */

#define CR_SATURN_CORE_REV_OFFSET                 (0x02D0)

/* Field CR_SATURN_MAINT_REV */
#define CR_SATURN_MAINT_REV_OFFSET                CR_SATURN_CORE_REV_OFFSET
#define CR_SATURN_MAINT_REV_SHIFT                 (0)
#define CR_SATURN_MAINT_REV_MASK                  (0x000000FF)
#define CR_SATURN_MAINT_REV_FLAGS                 (REG_VOL)
#define CR_SATURN_MAINT_REV_LENGTH                (8)

/* Field CR_SATURN_MINOR_REV */
#define CR_SATURN_MINOR_REV_OFFSET                CR_SATURN_CORE_REV_OFFSET
#define CR_SATURN_MINOR_REV_SHIFT                 (8)
#define CR_SATURN_MINOR_REV_MASK                  (0x0000FF00)
#define CR_SATURN_MINOR_REV_FLAGS                 (REG_VOL)
#define CR_SATURN_MINOR_REV_LENGTH                (8)

/* Field CR_SATURN_MAJOR_REV */
#define CR_SATURN_MAJOR_REV_OFFSET                CR_SATURN_CORE_REV_OFFSET
#define CR_SATURN_MAJOR_REV_SHIFT                 (16)
#define CR_SATURN_MAJOR_REV_MASK                  (0x00FF0000)
#define CR_SATURN_MAJOR_REV_FLAGS                 (REG_VOL)
#define CR_SATURN_MAJOR_REV_LENGTH                (8)

/* Field CR_SATURN_DESIGNER */
#define CR_SATURN_DESIGNER_OFFSET                 CR_SATURN_CORE_REV_OFFSET
#define CR_SATURN_DESIGNER_SHIFT                  (24)
#define CR_SATURN_DESIGNER_MASK                   (0xFF000000)
#define CR_SATURN_DESIGNER_FLAGS                  (REG_VOL)
#define CR_SATURN_DESIGNER_LENGTH                 (8)

/* Complete Register Definition */
#define CR_SATURN_CORE_REV_REG_OFFSET             CR_SATURN_CORE_REV_OFFSET
#define CR_SATURN_CORE_REV_REG_SHIFT              (0)
#define CR_SATURN_CORE_REV_REG_MASK               (0xFFFFFFFF)
#define CR_SATURN_CORE_REV_REG_FLAGS              (REG_VOL)
#define CR_SATURN_CORE_REV_REG_LENGTH             (32)


/* -------------------- Register CR_SATURN_CORE_DES1 -------------------- */

#define CR_SATURN_CORE_DES1_OFFSET                (0x02E0)

/* Field CR_SATURN_DESIGNER1 */
#define CR_SATURN_DESIGNER1_OFFSET                CR_SATURN_CORE_DES1_OFFSET
#define CR_SATURN_DESIGNER1_SHIFT                 (0)
#define CR_SATURN_DESIGNER1_MASK                  (0xFFFFFFFF)
#define CR_SATURN_DESIGNER1_FLAGS                 (REG_VOL)
#define CR_SATURN_DESIGNER1_LENGTH                (32)

/* Complete Register Definition */
#define CR_SATURN_CORE_DES1_REG_OFFSET            CR_SATURN_CORE_DES1_OFFSET
#define CR_SATURN_CORE_DES1_REG_SHIFT             (0)
#define CR_SATURN_CORE_DES1_REG_MASK              (0xFFFFFFFF)
#define CR_SATURN_CORE_DES1_REG_FLAGS             (REG_VOL)
#define CR_SATURN_CORE_DES1_REG_LENGTH            (32)


/* -------------------- Register CR_SATURN_CORE_DES2 -------------------- */

#define CR_SATURN_CORE_DES2_OFFSET                (0x02F0)

/* Field CR_SATURN_DESIGNER2 */
#define CR_SATURN_DESIGNER2_OFFSET                CR_SATURN_CORE_DES2_OFFSET
#define CR_SATURN_DESIGNER2_SHIFT                 (0)
#define CR_SATURN_DESIGNER2_MASK                  (0xFFFFFFFF)
#define CR_SATURN_DESIGNER2_FLAGS                 (REG_VOL)
#define CR_SATURN_DESIGNER2_LENGTH                (32)

/* Complete Register Definition */
#define CR_SATURN_CORE_DES2_REG_OFFSET            CR_SATURN_CORE_DES2_OFFSET
#define CR_SATURN_CORE_DES2_REG_SHIFT             (0)
#define CR_SATURN_CORE_DES2_REG_MASK              (0xFFFFFFFF)
#define CR_SATURN_CORE_DES2_REG_FLAGS             (REG_VOL)
#define CR_SATURN_CORE_DES2_REG_LENGTH            (32)

/* ------------------------ End of register definitions ------------------------ */

/*
// NUMREG defines the extent of register address space.
*/

#define     CR_PERIP_NUMREG     ((0x02F0 >> 2)+1)

/*-------------------------------------------------------------------------------*/

#ifdef __cplusplus
}
#endif

#endif /* __CR_PERIP_REG_DEFS_H__ */
