class CommonTvRegisters:
    TV_REG_API_VERSION,\
    TV_REG_DEMOD_ID,\
    TV_REG_BUILD_ID,\
    TV_REG_CONTROL,\
    TV_REG_STATE,\
    TV_REG_TUNER_FREQ,\
    TV_REG_TUNER_BW,\
    TV_REG_TUNER_GRID_BASE,\
    TV_REG_TUNER_GRID_INCR,\
    TV_REG_NOTCH_FREQ,\
    TV_REG_NOTCH_BW,\
    TV_REG_ACTIVE_TUNER_FREQ,\
    TV_REG_ACTIVE_TUNER_BW,\
    TV_REG_ACTIVE_TUNER_GAIN,\
    TV_REG_ACTIVE_TUNER_RSSI,\
    TV_REG_AGC_PARAMS,\
    TV_REG_FE_GROUP,\
    TV_REG_FE_CTRL,\
    TV_REG_FE_ADCSAMP,\
    TV_REG_FE_IF,\
    TV_REG_FE_RS,\
    TV_REG_FE_AGC_NORMAL,\
    TV_REG_FE_AGC_FAST,\
    TV_REG_FE_FIR_NARROW_0,\
    TV_REG_FE_FIR_NARROW_1,\
    TV_REG_FE_FIR_NARROW_2,\
    TV_REG_FE_FIR_NARROW_3,\
    TV_REG_FE_FIR_WIDE_0,\
    TV_REG_FE_FIR_WIDE_1,\
    TV_REG_FE_FIR_WIDE_2,\
    TV_REG_FE_FIR_WIDE_3,\
    TV_REG_TSO_CONFIG       = range(32)

StandardRegisterBase = 0x8000

class DVBS2Registers:
    DVBS2_REG_BAUD_RATE,\
    DVBS2_REG_MODULATION,\
    DVBS2_REG_CODE_RATE,\
    DVBS2_REG_PILOTS_PRESENT,\
    DVBS2_RRC_ROLLOFF_FACTOR,\
    DVBS2_REG_ACTIVE_BAUD_RATE,\
    DVBS2_REG_ACTIVE_MODULATION,\
    DVBS2_REG_ACTIVE_CODE_RATE,\
    DVBS2_REG_ACTIVE_PILOTS_PRESENT,\
    DVBS2_REG_ACTIVE_ROLLOFF_FACTOR,\
    DVBS2_REG_FER_AT_LDPC_OUTPUT,\
    DVBS2_REG_BER_AT_BCH_INPUT,\
    DVBS2_REG_FER_AT_BCH_OUTPUT,\
    DVBS2_REG_PER_AT_OUTPUT,\
    DVBS2_REG_NUM_SECONDS_BER_AVERAGING,\
    DVBS2_REG_TS_PACKET_COUNT,\
    DVBS2_REG_BAD_PACKET_COUNT,\
    DVBS2_REG_BIT_RATE,\
    DVBS2_REG_SNR_ESTIMATE,\
    DVBS2_CARRIER_FREQ_SEARCH_RANGE,\
    DVBS2_SYMBOL_RATE_SEARCH_RANGE,\
    DVBS2_REG_ACQUISITION_STATE,\
    DVBS2_REG_NUM_ACQUISITIONS,\
    DVBS2_REG_ACQUISITION_FAILURE_CODE,\
    DVBS2_REG_ERROR_CODE,\
    DVBS2_REG_I_AMP,\
    DVBS2_REG_Q_AMP,\
    DVBS2_REG_ANALOG_GAIN,\
    DVBS2_REG_DIGITAL_GAIN,\
    DVBS2_REG_ACQUISITION_TIME,\
    DVBS2_REG_CARRIER_FREQ_OFFSET,\
    DVBS2_REG_CTRL,\
    DVBS2_REG_MANUAL_DFE_COEFFS00,\
    DVBS2_REG_MANUAL_DFE_COEFFS01,\
    DVBS2_REG_MANUAL_DFE_COEFFS02,\
    DVBS2_REG_MANUAL_DFE_COEFFS03,\
    DVBS2_REG_MANUAL_DFE_COEFFS04,\
    DVBS2_REG_MANUAL_DFE_COEFFS05,\
    DVBS2_REG_MANUAL_DFE_COEFFS06,\
    DVBS2_REG_MANUAL_DFE_COEFFS07,\
    DVBS2_REG_MANUAL_DFE_COEFFS08,\
    DVBS2_REG_MANUAL_DFE_COEFFS09,\
    DVBS2_REG_MANUAL_DFE_COEFFS10,\
    DVBS2_REG_MANUAL_DFE_COEFFS11,\
    DVBS2_REG_MANUAL_DFE_COEFFS12,\
    DVBS2_REG_MANUAL_DFE_COEFFS13,\
    DVBS2_REG_MANUAL_DFE_COEFFS14,\
    DVBS2_REG_MANUAL_DFE_COEFFS15,\
    DVBS2_REG_SPECTRUM_INVERSION,\
    DVBS2_REG_ACTIVE_SPECTRUM_INVERSION,\
    DVBS2_REG_CLOCKING_INFO,\
    DVBS2_REG_TUNED_FREQ_OFFSET = range(StandardRegisterBase, StandardRegisterBase + 52)
    
class DVBSRegisters:
    DVBS_REG_BAUD_RATE,\
    DVBS_REG_CODE_RATE,\
    DVBS_REG_ACTIVE_BAUD_RATE,\
    DVBS_REG_ACTIVE_CODE_RATE,\
    DVBS_REG_BER_AT_VITERBI_INPUT,\
    DVBS_REG_BER_AT_RS_INPUT,\
    DVBS_REG_PER_AT_OUTPUT,\
    DVBS_REG_NUM_SECONDS_BER_AVERAGING,\
    DVBS_REG_TS_PACKET_COUNT,\
    DVBS_REG_BAD_PACKET_COUNT,\
    DVBS_REG_BIT_RATE,\
    DVBS_REG_SNR_ESTIMATE,\
    DVBS_CARRIER_FREQ_SEARCH_RANGE,\
    DVBS_SYMBOL_RATE_SEARCH_RANGE,\
    DVBS_REG_ACQUISITION_STATE,\
    DVBS_REG_NUM_ACQUISITIONS,\
    DVBS_REG_ACQUISITION_FAILURE_CODE,\
    DVBS_REG_ERROR_CODE,\
    DVBS_REG_I_AMP,\
    DVBS_REG_Q_AMP,\
    DVBS_REG_ANALOG_GAIN,\
    DVBS_REG_DIGITAL_GAIN,\
    DVBS_REG_ACQUISITION_TIME,\
    DVBS_REG_CARRIER_FREQ_OFFSET,\
    DVBS_REG_CTRL,\
    DVBS_REG_MANUAL_DFE_COEFFS00,\
    DVBS_REG_MANUAL_DFE_COEFFS01,\
    DVBS_REG_MANUAL_DFE_COEFFS02,\
    DVBS_REG_MANUAL_DFE_COEFFS03,\
    DVBS_REG_MANUAL_DFE_COEFFS04,\
    DVBS_REG_MANUAL_DFE_COEFFS05,\
    DVBS_REG_MANUAL_DFE_COEFFS06,\
    DVBS_REG_MANUAL_DFE_COEFFS07,\
    DVBS_REG_MANUAL_DFE_COEFFS08,\
    DVBS_REG_MANUAL_DFE_COEFFS09,\
    DVBS_REG_MANUAL_DFE_COEFFS10,\
    DVBS_REG_MANUAL_DFE_COEFFS11,\
    DVBS_REG_MANUAL_DFE_COEFFS12,\
    DVBS_REG_MANUAL_DFE_COEFFS13,\
    DVBS_REG_MANUAL_DFE_COEFFS14,\
    DVBS_REG_MANUAL_DFE_COEFFS15,\
    DVBS_REG_SPECTRUM_INVERSION,\
    DVBS_REG_ACTIVE_SPECTRUM_INVERSION,\
    DVBS_REG_TUNED_FREQ_OFFSET  = range(StandardRegisterBase, StandardRegisterBase + 44)

class UCCStandards:
    UCC_STANDARD_NOT_SIGNALLED,\
    UCC_STANDARD_DVBT,\
    UCC_STANDARD_DVBH,\
    UCC_STANDARD_ISDBT_1SEG,\
    UCC_STANDARD_ISDBT_3SEG,\
    UCC_STANDARD_ISDBT_13SEG,\
    UCC_STANDARD_DAB,\
    UCC_STANDARD_FM,\
    UCC_STANDARD_ATSC,\
    UCC_STANDARD_DVBC,\
    UCC_STANDARD_J83B,\
    UCC_STANDARD_ISDBC,\
    UCC_STANDARD_DVBT2,\
    UCC_STANDARD_DVBS,\
    UCC_STANDARD_DVBS2,\
    UCC_STANDARD_ISDBS,\
    UCC_STANDARD_GB206,\
    UCC_STANDARD_ATV,\
    UCC_STANDARD_SPECTRUM_ANALYSER,\
    UCC_STANDARD_STOP_REQUEST= range(20)
    
class CodeRates:
    HALF,\
    TWO_THIRDS,\
    THREE_QUARTERS,\
    FIVE_SIXTHS,\
    SEVEN_EIGHTH,\
    THREE_FIFTHS,\
    FOUR_FIFTHS,\
    EIGHT_NINTHS,\
    NINE_TENTHS = range(9)
    
# Helper function to lookup one of the "enum" classes above
def lookupEnum(enumDefinition, value):
    lookup = enumDefinition.__dict__

    k = lookup.keys()
    v = lookup.values()
    
    for idx,d in enumerate(v):
        if value == d:
            key = k[idx]
            return key
    
    return "NA"
    